name: Deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy snake on FTP
    runs-on: ubuntu-latest
    steps:

    - name: Get latest code
      uses: actions/checkout@v2.4.0
    
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }} 
        local-dir: ./dist/
        exclude: .git* .git*/** node_modules/** node_modules/**/* *.md